### PR TITLE
Support TypeScript 2.9.x

### PR DESCRIPTION
**Pull request by rpetrich**
Update the dependency and fix resulting issues related to type formatting

### CODE REVIEW

**Comment by domoritz** [comment]
Can you resolve the issues and fix the build? It'd be great to merge this.

**Comment by rpetrich** [comment]
@domoritz this should be ready to go.

I had to introduce a symbol hashing function to make the `unique-names` test deterministic as Travis was getting different symbol IDs than my local installs.

Also, we may want to update the tsnode dependencies now that the bundled TypeScript is 2.9.x

**Comment by rpetrich** [comment]
@domoritz ts-node is now updated to 7.0.0

**Comment by domoritz** [comment]
Thank you!

**Pull request merged**
