### PR TITLE
fix the compile error

### PR DESCRIPTION
**Pull request by beeing**
Please:
- [ ] Do not include the compiled `.js`, `.js.map`, or `.d.ts` in your pull request as it makes it harder to merge your changes. 
- [x] Make your pull request atomic, fixing one issue at a time unless there are many relevant issues that cannot be decoupled.
- [ ] Provide a test case & update the documentation in the `Readme.md`

### CODE REVIEW

**Comment by domoritz** [comment]
Can you remove the compiled files so I can merge this pr?

**Comment by beeing** [comment]
I’m sorry, but how do I do that?

**Comment by domoritz** [comment]
Just delete the file and commit the changes (`git add -A`).

**Comment by beeing** [comment]
done

**Pull request closed without merging**
