### PR TITLE
fix: top-level alias type comments parse

### PR DESCRIPTION
**Pull request by ExcitedSpider**
Please:
- [x] Make your pull request atomic, fixing one issue at a time unless there are many relevant issues that cannot be decoupled.
- [ ] Provide a test case & update the documentation in the `Readme.md`

As discussed in #394 , parse comment for top-level type.

### CODE REVIEW

**Comment by domoritz** [comment]
Thank you for the pull request. Can you please fix the test cases? You can either correct the specs if that's needed or fix the code.

**Comment by ExcitedSpider** [comment]
OK, I'll do it.

**Comment by ExcitedSpider** [comment]
Hi, I've corrected the test case by adding the parsed comment for `type` alias.

**Comment by domoritz** [comment]
fixes #394

**Pull request merged**
