### PR TITLE
use const instead of enum

### PR DESCRIPTION
**Pull request by lublak**
Please:
- [x] Make your pull request atomic, fixing one issue at a time unless there are many relevant issues that cannot be decoupled.
- [x] Provide a test case & update the documentation in the `Readme.md`

fixes https://github.com/YousefED/typescript-json-schema/issues/534

### CODE REVIEW

**Comment by domoritz** [comment]
Please remove the npm lock file

**Comment by lublak** [comment]
@domoritz done

**Comment by domoritz** [comment]
Tests are failing

**Comment by lublak** [comment]
@domoritz can you try again

**Comment by domoritz** [comment]
Why should we make this configurable? I feel it's a better default and would like it always enabled. What do you think?

**Comment by lublak** [comment]
@domoritz then it is not compatible with your tests. (backwards compatible?)

**Comment by domoritz** [comment]
Of we think this is better then we can release a new breaking version.

One question? How does this work if you have an enum with one value?

**Comment by domoritz** [comment]
And speaking of tests, we need one.

**Comment by lublak** [comment]
@domoritz the issue ist currenlty: The complete project doesn't work. If i just try npm test, the tests are currently failing (and no i have not really time to fix all issues).
Okay a breaking version can be fine for this.
If you have a enum with one value it works fine with most stuff.
But const is here a better solution. After all, that's what const is for.

**Comment by domoritz** [comment]
You can just add one test and run that wither by marking the test as `.only` or commenting out the others.

**Comment by lublak** [comment]
@domoritz i changed now the tests and its now a breaking change.

**Comment by domoritz** [comment]
Please fix the tests so we can merge this.

**Comment by lublak** [comment]
@domoritz yes!
The issue is, if i run my test local i can not see all issues directly. So i only can see if its fails here.
My local test looks like this:

grafik
grafik

but i hope i can fix it without testing it.

**Comment by lublak** [comment]
@domoritz can you try again? :)

**Pull request merged**
