### PR TITLE
Issue #113: @TJS-format now fully supported.

### PR DESCRIPTION
**Pull request by robertmassaioli**
I have included a test case and verified that it fails if the correction is not made:

screen shot 2017-05-24 at 1 44 04 pm

This is a simple fix and should resolve this issue. It would be great if it could be merged and released soon. 😄  Thanks!

### CODE REVIEW

**Comment by domoritz** [comment]
Thank you for the pull request!

**Comment by robertmassaioli** [comment]
No problems @domoritz; happy to help! When can I hope to see a release of this library that includes this? It would be great to have that fix available via NPM: https://www.npmjs.com/package/typescript-json-schema

**Comment by domoritz** [comment]
I just made a release v0.12.0

**Comment by robertmassaioli** [comment]
Champion! Thankyou! I appreciate it. If I spot any other bug fixes I'll be sure to raise a PR.

**Pull request merged**
