### PR TITLE
feat: add bigint primitive type

### PR DESCRIPTION
**Pull request by SamuelScheit**
source:
```ts
class MyObject {
    bigint1: bigint;
}
```

translates to:
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "bigint1": {
            "type": "bigint"
        }
    }
}
```

- [x] I've updated the ``test-primitives`` test

### CODE REVIEW

**Comment by domoritz** [comment]
Can you fix the tests?

**Comment by Flam3rboy** [comment]
idk how, can you help me with that?

**Comment by LukasDoesDev** [comment]
@Flam3rboy Can you run the test yourself and add `console.log('AJV Errors:', ajv.errors);` before `assert.equal(ajv.errors, null, "The schema is not valid");` in the `test/schema.test.ts` file? You could get more information on the errors that way.

**Comment by domoritz** [comment]
If you run `yarn test`, you will see the test failures locally as well.

**Comment by carleryd** [comment]
Any updates here? This is blocking me now. Perhaps I will open a PR since this looks inactive

**Comment by xdumaine** [comment]
this resolved an issue for me too, just FYI, would love to help get this finished and merged.

**Comment by domoritz** [comment]
Can you make a new pull request? I'll close this as the tests didn't run.

**Pull request closed without merging**
