### PR TITLE
Adding more validation keywords.

### PR DESCRIPTION
**Pull request by robertmassaioli**
In this pull request I have added in minProperties and maxProperties and also indicated which validation keywords from the spec are not available.

I am having trouble running the tests locally because of [this issue](https://stackoverflow.com/questions/39116687/error-ts2304-cannot-find-name-promise) but I will try and add tests soon.

### CODE REVIEW

**Comment by robertmassaioli** [comment]
I don't know why that one test in the build is failing. It works for me locally and it is the other tests that fail. Weird.

**Comment by domoritz** [comment]
The error is weird. I restarted the build. Let's see.

**Comment by robertmassaioli** [comment]
Yay! It went green that time. 😄  Thanks @domoritz

**Comment by robertmassaioli** [comment]
Thank you, much appreciated! I look forward to using the next release!

**Comment by nicolasv** [comment]
I'd love to be able to use some of the keywords from this change — any chance of a new release, please?

**Comment by domoritz** [comment]
Deployed as v0.14

**Pull request merged**
