### PR TITLE
Include proper declaration files in NPM package

### PR DESCRIPTION
**Pull request by felixfbecker**
1. Changes typescript-json-schema to be an external (ES6) module (the diff is large but only the indentation changed)
2. Adds .d.ts files
3. Adds a .npmignore that ignores the TypeScript source and typings needed for development

See #49 and https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html

I did not add the .d.ts to .gitignore because you also don't have the JS files in there, so I suppose you want to support installing from GitHub directly.

### CODE REVIEW

**Comment by felixfbecker** [comment]
Hold off, I just saw that it is not generating an external module...

**Comment by felixfbecker** [comment]
ping @YousefED

**Comment by YousefED** [comment]
Thanks, sorry for the delay.

Would it be possible to file the changes without the indentation changes? This will make it difficult to merge with other outstanding PRs

**Comment by felixfbecker** [comment]
Hm, maybe. But it would not be very nice programatic usage because you cannot cherry-pick the functions to import, you _always_ have to import the whole namespace, which doesn't make much sense given it is the only thing that is exported. Internal `module` syntax has been deprecated for quite some time now, so I think this would be a change for the good... Other PRs would have to rebase of course. If there are any particular PRs you want to merge, you can also merge them first and then ping me and I do the work of rebasing this? I favor cleaner code over saving some work.

Thanks for the response

**Comment by YousefED** [comment]
Thanks, will ping

**Comment by YousefED** [comment]
done! Let me know when this is ready to merge

**Comment by felixfbecker** [comment]
Successfully rebased on latest master (including all the latest PR merges).

**Comment by felixfbecker** [comment]
ping @YousefED

**Comment by domoritz** [comment]
Sorry to ask you again but can you rebase your pr again? I'll merge it as soon as you do it. Thanks!

**Comment by domoritz** [comment]
ping @felixfbecker. I'll merge as soon as you rebase to avoid future conflicts.

**Comment by felixfbecker** [comment]
@domoritz rebased 👍

**Comment by domoritz** [comment]
I trust that only indentation changed ;-)

**Comment by felixfbecker** [comment]
@domoritz Well all tests pass - but I would recommend you to enable required status checks for PRs, since you are already using Travis 😉

**Pull request merged**
