### PR TITLE
Basic type comment functionality

### PR DESCRIPTION
**Pull request by low-ghost**
This pull request adds basic type comment support such that properties added to a type will be carried over into interfaces. E.g.
```js
/**
 * @type integer
 * @minimum 1
 */
export type PositiveInteger = number;

export interface MyObject {
  user_ids: PositiveInteger[];
}
```
See comments-override-types for tests.
This gets us some of the way, but test comments-override-types-tuples fails and may need a substantial rewrite. See issue [57](https://github.com/YousefED/typescript-json-schema/issues/57)

### CODE REVIEW

**Comment by domoritz** [comment]
Please don't include changes to the .js and .js.map files in prs. It'll make it harder to merge.

**Comment by low-ghost** [comment]
Sure, reverted those changes. Also, this change makes types ref-able, so it changes the functionality a bit. You might want to check the changes to test files and make sure that these changes are ok.

**Comment by domoritz** [comment]
Looks good to me but it doesn't seem to work with type unions.

```ts
/**
 * An integer greater than one
 * @type integer
 * @minimum 1
 */
export type PositiveInteger = number;

foo: PositiveInteger | string;
```

Generates

```json
"foo": {
            "type": [
                "string",
                "number"
            ]
        },
```

**Comment by low-ghost** [comment]
Yeah, the more I look at it, the less this change supports. Not worth adding in these changes just to have to make more substantial, less messy changes latter on. Working on some things now-ish and over the weekend perhaps

**Comment by domoritz** [comment]
Thanks @low-ghost!

**Pull request closed without merging**
