### PR TITLE
A few fixes and features, and TypeScript 2 support

### PR DESCRIPTION
**Pull request by otgerrogla**
Changes:

  - Fixed bug reported in #44 where _additionalProperties_ was being added to the property instead of the type. Checked with new test "comment-override".
    
  - Support for intersection types (issue #46). Created test "type-intersection".
  
  - Added a way to export all definitions of a file, by passing as argument `*` instead of a fully qualified type name. It generates a schema with just the "definitions" section, that includes all user-defined types parsed. (implements feature requested in #51)
  
  - Small improvement: unions of simple types like `val: number | string` now generate:
      `` "val": { "type": [ "number", "string" ] } ``
    Instead of a full "oneOf"/"anyOf" definition
    Updated test "type-union" to test both cases now, and some other tests that failed due to this change
    
  - Partial support for Typescript 2 **null**/**undefined** types (asked in #48) Added argument `strictNullChecks` (the same name used in **tsc**), which is inserted in the default CompilerOptions if provided, to enable the non-nullable-by-default behavior. Some minor changes done so that all tests pass now for both TS 1.8 and 2.0. A new test "typescript-2" is only run when 2.0 is used, and checks the null/undefined types
    
  - For compatibility (and for use in non-strictNullChecks mode), also added a @nullable annotation as requested in #36, and its test "type-nullable"

### CODE REVIEW

**Comment by MarcusRiemer** [comment]
Wow, your `comments-override` test shows that you have exactly nailed an issue about overriding `additionalProperties` on a per-field basis that I was just about to open. Thanks a lot for your work, you have just saved me some precious time that I can now invest in my master's thesis.

**Comment by YousefED** [comment]
Thanks, 

- just to make sure: "val": { "type": [ "number", "string" ] }, do you know where I can find this syntax in the JSON schema spec? Looks good, but let's make sure it corresponds to anyOf, as we just switched to anyOf as default unionModifier (probably also causing the conflict now.
- I'm looking for new maintainers, as the projects I'm working on are not actively using TJS at this moment. Let me know if you're interested

**Comment by otgerrogla** [comment]
I've done another commit fixing the conflicts, and also fixed a pair of bugs with enums (and added a test "enums-mixed")

The `"val": { "type": [ "number", "string" ] }` is covered in http://json-schema.org/latest/json-schema-validation.html#anchor79 :

> 5.5.2.  type

> 5.5.2.1.  Valid values
> The value of this keyword MUST be either a string or an array. If it is an array, elements of the array MUST be strings and MUST be unique.
> String values MUST be one of the seven primitive types defined by the core specification.

> 5.5.2.2.  Conditions for successful validation
> An instance matches successfully if its primitive type is one of the types defined by keyword. Recall: "number" includes "integer"


I can have a look at the issues now and then, but I'm not sure if I'll have much free time.

**Comment by YousefED** [comment]
Thanks, I found http://json-schema.org/latest/json-schema-validation.html#anchor79, but it doesn't mention how it should be interpreted.

I'll merge the request

**Comment by YousefED** [comment]
closes #44 #46 #51 #48 #36

**Comment by YousefED** [comment]
closes #44 
closes #46 
closes #51 
closes #48 
closes #36

**Comment by low-ghost** [comment]
Huh, I was also concerned about mixed enums. Didn't know you could specify 'type' as an array and thought it'd have to be anyOf or something. And, I too was trying to solve the comments-override problem. Awesome work

**Pull request merged**
